stages:
- test
- name: deploy
  if: branch = optimize/compatitable
language: cpp
sudo: required
dist: trusty
git:
  depth: false
os:
- linux
fast_finish: true
# branches:
  # only: master
cache:
  directories:
  - gcc-linaro-5.5.0-2017.10-x86_64_aarch64-linux-gnu/
  - sysroot-glibc-linaro-2.21-2017.10-aarch64-linux-gnu/
  - gcc-linaro-5.5.0-2017.10-x86_64_arm-linux-gnueabi/
  - sysroot-glibc-linaro-2.21-2017.10-arm-linux-gnueabi/
install:
- sudo apt-get update -q
- sudo apt-get install wget -q -y
- which gcc
- which g++
jobs:
  include:
  - stage: tests
    name: aarch64-linux-gnu
    script: tools/install-toolchain-sysroot.sh aarch64-linux-gnu
      - tools/build.sh --host aarch64-linux-gnu --toolchain ${aarch64_toolchain_name}/bin --sysroot ${aarch64_sysroot_name} -j 8 -s
  - script: tools/install-toolchain-sysroot.sh arm-linux-gnueabi
      - tools/build.sh --host arm-linux-gnueabi --toolchain ${armhf_toolchain_name}/bin --sysroot ${armhf_sysroot_name} -j 8 -s
    name: arm-linux-gnueabi
  - script: tools/build.sh -j 8 -s
    name: linux x86_64
  - stage: deploy
    name: Deploy to Github
    script: echo "Deploying to GitHub releases ..."
      - tools/install-toolchain-sysroot.sh
      - tools/build.sh --host aarch64-linux-gnu --toolchain ${aarch64_toolchain_name}/bin --sysroot ${aarch64_sysroot_name} -j 8 -s
      - tools/build.sh --host arm-linux-gnueabi --toolchain ${armhf_toolchain_name}/bin --sysroot ${armhf_sysroot_name} -j 8 -s
      - tools/build.sh -j 8 -s
      - mkdir release
      - cp build-x86_64/yoda-sixsix release/yoda-sixsix-linux_x86_64
      - cp build-aarch64-linux-gnu/yoda-sixsix release/yoda-sixsix-aarch64-linux-gnu
      - cp build-arm-linux-gnueabi/yoda-sixsix release/yoda-sixsix-arm-linux-gnueabi
      - tar -czf yoda-sixsix-release.tar.gz release/
      - ls -lh
    deploy:
      provider: releases
      api_key:
        secure: jKqMCzdzwf6DWBt8HT9s2k2SrFHeOlZZaGUreMl/TQNQzw+Z/40vPfq+e52c0/bszPLda8AKeaj+/FOStUe3mY++jaLi4ks9g3hz+vykG3LnNPYyu7ahi5nAQJtQxnyR1DkRpN8ex2FWdWTUT1dRui5SxaA7DVIkQlDFm0JzPD91rpEwVF14oFNGG+0SG5n6cMdmp2//2MXKuT3XhRzHY+IfoC6jOD8r6nEmNwcPvRiEVUV7idnaPBHZDF5cBAmdGl8+HkWkUGv3nuC2iV7jCLtBRQgeBuuthuiACC5FkjftXnj8aKuZng7lOYllgm3HdCGE8Lejs7iugASeH9LxFuz2cb29tDvisW7XDqMQvgJl9O7LXP7jTsSkAausl+M97ROSeVq59LpOElH8mURLSjCT+y+7fs/27quREzalbEtc6VfRac+ObdcKYkcquKDbZtl/cjH0NEe5GiouatVvXgu8elu5UyXwrd7YaP5Gil2e6aNRMegVVwyJuilk3cb3XfLazhPrTsAffW+1PViryFWK1VLeDqRgT/YwMXLo+m6ddCwk0b/j99Ile6lj5/zimpvFoP3P1Pk3KGtiWcUmxzO1/n9WnsZM9dqysLeIFWUsfkUP9XJmlGRwur4lKfXhjVQl+QgmH0W6BFmhu0Ab96QMyjfpW1UX1wSHeXDvlX0=
      file: yoda-sixsix-release.tar.gz
      on:
        repo: yodaos-project/edge-monitor
        branch: optimize/compatitable
