language: cpp
sudo: required
dist: trusty
git:
  depth: false
os:
  - linux
  - osx
compiler:
  - gcc
branches:
  only:
    - master
#     - ci

before_install:
# 
script:
  - sudo apt-get update
  - sudo apt-get install gcc-aarch64-linux-gnu
  - sudo apt-get install gcc-arm-linux-gnueabi
  - cmake -H. -B./build
  - make -C./build
